/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status API dan OpenTripPlanner */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cari opsi perjalanan antara dua titik */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cari tempat di Jabodetabek */
        get: operations["searchPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Status: {
            /** @constant */
            api: "ok";
            otp: {
                /** @description Apakah OpenTripPlanner bisa dihubungi. */
                reachable: boolean;
                /** @description ID feed GTFS yang dimuat OTP (misal TJ, KRL). */
                feeds: string[];
            };
        };
        Plan: {
            itineraries: components["schemas"]["Itinerary"][];
            /** @description ID itinerary dari terbaik ke terburuk untuk tiap preferensi. */
            ranking: {
                tercepat: string[];
                termurah: string[];
                termudah: string[];
            };
        };
        Itinerary: {
            id: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            durationSec: number;
            walkDistanceM: number;
            transfers: number;
            fare: {
                totalIdr: number;
                /** @description false jika ada moda tanpa data tarif, sehingga totalIdr adalah batas bawah. */
                complete: boolean;
            };
            legs: components["schemas"]["Leg"][];
        };
        Leg: {
            /** @description Moda OTP, misal WALK, BUS, RAIL, SUBWAY, TRAM. */
            mode: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            durationSec: number;
            distanceM: number;
            from: components["schemas"]["Place"];
            to: components["schemas"]["Place"];
            route: components["schemas"]["Route"] | null;
            /** @description Dibayar saat naik leg ini. 0 jika tercakup tiket sebelumnya, null untuk jalan kaki atau tarif tidak diketahui. */
            fareIdr: number | null;
            /** @description Jalur leg sebagai pasangan [lon, lat]. */
            geometry: number[][];
        };
        Place: {
            name: string;
            lat: number;
            lon: number;
        };
        PlaceResult: {
            id: string;
            name: string;
            address: string;
            lat: number;
            lon: number;
        };
        Route: {
            id: string;
            shortName: string;
            longName: string;
            /** @description Kategori layanan dari GTFS, misal BRT, Mikrotrans, Royaltrans. */
            category: string;
            /** @description Warna hex dengan '#', bisa kosong. */
            color: string;
            textColor: string;
            agency: string;
        };
    };
    responses: {
        /** @description Pesan galat yang bisa langsung ditampilkan ke pengguna. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API hidup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status layanan. Selalu 200 agar web app bisa menampilkan mode terbatas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    getPlan: {
        parameters: {
            query: {
                fromLat: number;
                fromLon: number;
                fromName?: string;
                toLat: number;
                toLon: number;
                toName?: string;
                /** @description Waktu berangkat (RFC 3339). Default sekarang. */
                time?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opsi perjalanan. Daftar kosong berarti tidak ada rute. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    searchPlaces: {
        parameters: {
            query: {
                /** @description Kata kunci, minimal 2 karakter. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tempat yang cocok, paling relevan dulu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        places: components["schemas"]["PlaceResult"][];
                    };
                };
            };
            502: components["responses"]["Error"];
        };
    };
}
